kind: pipeline
type: docker
name: default
   
steps:
- name: build
  image: chindou/operator-sdk-image:latest
  commands:
    - apk add --update --no-cache vim git make musl-dev go curl gcc build-base
    # Configure Go
    - export GOPATH=/root/go
    - export PATH=${GOPATH}/bin:/usr/local/go/bin:$PATH
    - export GOBIN=$GOROOT/bin
    - mkdir -p ${GOPATH}/src ${GOPATH}/bin
    - export GO111MODULE=on
    - go version
    - operator-sdk build kafka-autoconnector:latest