kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src/kafka-autoconnector
   
steps:
- name: build
  pull: always
  image: golang:alpine
  commands:
    - apk update && apk --no-cache add git dep ca-certificates musl-dev gcc build-base
    - CGO_ENABLED=0 go build -o ./build/_output/bin/kafka-autoconnector -gcflags all=-trimpath=/drone/src -asmflags all=-trimpath=/drone/src github.com/walmartdigital/kafka-autoconnector/cmd/manager

- name: docker
  pull: always
  image: plugins/docker
  settings:
    dockerfile: build/Dockerfile
    repo: walmartdigital/kafka-autoconnector
    tags:
      - latest
      - ${DRONE_TAG}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    trigger:
      branch:
      - master
      event:
      - tag
  