apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: kafka-autoconnector
build:
  local: {}
  artifacts:
  - image: kafka-autoconnector
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
        - .
    
deploy:
  kubectl:
    manifests:
    - deploy/role_binding.yaml
    - deploy/role.yaml
    - deploy/service_account.yaml
    - deploy/crds/skynet.walmartdigital.cl_genericautoconnectors_crd.yaml
    - deploy/crds/skynet.walmartdigital.cl_essinkconnectors_crd.yaml
    - deploy/crds/skynet.walmartdigital.cl_kafkaconnectconfigs_crd.yaml
    - deploy/operator.yaml
