apiVersion: skynet.walmartdigital.cl/v1alpha1
kind: GenericAutoConnector
metadata:
  name: example-connector
  namespace: default
spec:
  connector.config:
    connector.class: "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector"
    type.name: "log"
    topics: "dumblogger-logs,_ims.logs,_amida.logs,_osiris.logs,_midas.logs,_kimun.logs"
    topic.index.map: "dumblogger-logs:<logs-pd-dumblogger-{now/d}>,_ims.logs:<logs-pd-ims-{now/d}>,_amida.logs:<logs-pd-amida-{now/d}>,_osiris.logs:<logs-pd-osiris-{now/d}>,_midas.logs:<logs-pd-midas-{now/d}>,_kimun.logs:<logs-pd-kimun-{now/d}>"
    connection.url: "http://elasticsearch-master:9200"
    connection.username: "${vault:secret/underworld/kafka-connect/tools/elasticlogs:username}"
    connection.password: "${vault:secret/underworld/kafka-connect/tools/elasticlogs:password}"
    key.ignore: "true"
    schema.ignore: "true"
    behavior.on.malformed.documents: "ignore"
    batch.size: "200"
    max.in.flight.requests: "5"
    max.buffered.records: "20000"
    linger.ms: "1"
    flush.timeout.ms: "10000"
    max.retries: "5"
    retry.backoff.ms: "100"
    connection.compression: "false"
    connection.timeout.ms: "1000"
    read.timeout.ms: "3000"
    max.tasks: "2"