// Code generated by MockGen. DO NOT EDIT.
// Source: metrics.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	metrics "github.com/walmartdigital/kafka-autoconnector/pkg/metrics"
	reflect "reflect"
)

// MockMetrics is a mock of Metrics interface
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// InitMetrics mocks base method
func (m *MockMetrics) InitMetrics() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InitMetrics")
}

// InitMetrics indicates an expected call of InitMetrics
func (mr *MockMetricsMockRecorder) InitMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitMetrics", reflect.TypeOf((*MockMetrics)(nil).InitMetrics))
}

// IncrementCounter mocks base method
func (m *MockMetrics) IncrementCounter(arg0 string, arg1 ...string) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "IncrementCounter", varargs...)
}

// IncrementCounter indicates an expected call of IncrementCounter
func (mr *MockMetricsMockRecorder) IncrementCounter(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCounter", reflect.TypeOf((*MockMetrics)(nil).IncrementCounter), varargs...)
}

// ResetCounter mocks base method
func (m *MockMetrics) ResetCounter(arg0 string, arg1 ...string) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ResetCounter", varargs...)
}

// ResetCounter indicates an expected call of ResetCounter
func (mr *MockMetricsMockRecorder) ResetCounter(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetCounter", reflect.TypeOf((*MockMetrics)(nil).ResetCounter), varargs...)
}

// SetGauge mocks base method
func (m *MockMetrics) SetGauge(arg0 string, arg1 float64, arg2 ...string) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "SetGauge", varargs...)
}

// SetGauge indicates an expected call of SetGauge
func (mr *MockMetricsMockRecorder) SetGauge(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGauge", reflect.TypeOf((*MockMetrics)(nil).SetGauge), varargs...)
}

// AddToGauge mocks base method
func (m *MockMetrics) AddToGauge(arg0 string, arg1 float64, arg2 ...string) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddToGauge", varargs...)
}

// AddToGauge indicates an expected call of AddToGauge
func (mr *MockMetricsMockRecorder) AddToGauge(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToGauge", reflect.TypeOf((*MockMetrics)(nil).AddToGauge), varargs...)
}

// DestroyMetrics mocks base method
func (m *MockMetrics) DestroyMetrics() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DestroyMetrics")
}

// DestroyMetrics indicates an expected call of DestroyMetrics
func (mr *MockMetricsMockRecorder) DestroyMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyMetrics", reflect.TypeOf((*MockMetrics)(nil).DestroyMetrics))
}

// MockMetricsFactory is a mock of MetricsFactory interface
type MockMetricsFactory struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsFactoryMockRecorder
}

// MockMetricsFactoryMockRecorder is the mock recorder for MockMetricsFactory
type MockMetricsFactoryMockRecorder struct {
	mock *MockMetricsFactory
}

// NewMockMetricsFactory creates a new mock instance
func NewMockMetricsFactory(ctrl *gomock.Controller) *MockMetricsFactory {
	mock := &MockMetricsFactory{ctrl: ctrl}
	mock.recorder = &MockMetricsFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMetricsFactory) EXPECT() *MockMetricsFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockMetricsFactory) Create() metrics.Metrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create")
	ret0, _ := ret[0].(metrics.Metrics)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockMetricsFactoryMockRecorder) Create() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMetricsFactory)(nil).Create))
}
